[package]
name = "axal-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
alloy = "1.0.33"
axum = "0.8.5"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
tower-http = { version = "0.5", features = ["cors"] }
